name: Deploy do Projeto

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main"]

jobs:
  validacao-estatica:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Checar arquivos estaticos
        run: |
          ls -R
          echo "Todos os arquivos foram carregados no Runner!"

      - name: Validar sintaxe HTML
        run: npx htmlhint index.html